# Bu iş akışının adı
name: Build, Test, and Release Automation

# Bu iş akışını ne zaman çalıştıracağını belirler
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- AŞAMA 1: DAĞITIM PAKETİNİ OLUŞTURMA ---
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Extract Tesseract Portable
        run: |
          curl -L -o tesseract.zip "https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.3.3.20231005.exe"
          7z x tesseract.zip -oTesseractOCR

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run PyInstaller to build the EXE
        run: pyinstaller --name "Automation" --onefile --windowed --add-data "isim_label.png;." automation.py

      - name: Prepare Release Folder Structure
        run: |
          mkdir release_package
          mkdir release_package/tesseract
          Copy-Item -Path "TesseractOCR/*" -Destination "release_package/tesseract" -Recurse
          Copy-Item -Path "dist/Automation.exe" -Destination "release_package/"
          Copy-Item -Path "isim_label.png" -Destination "release_package/"
      
      - name: Get Version Number
        id: version
        run: echo "tag=v1.0.${{ github.run_number }}" >> $env:GITHUB_OUTPUT

      - name: Zip the Release Folder
        run: Compress-Archive -Path release_package/* -DestinationPath "InsaatAsistani-${{ steps.version.outputs.tag }}.zip"

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-package
          path: "InsaatAsistani-${{ steps.version.outputs.tag }}.zip"

  # --- AŞAMA 2: OLUŞTURULAN PAKETİ TEST ETME ---
  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-release-package

      - name: Unzip Release Package
        run: Expand-Archive -Path "*.zip" -DestinationPath test_run

      - name: Run Integration Test
        env:
          PYTHONUTF8: "1"
        run: |
          echo "Hedef uygulama başlatılıyor..."
          Start-Process python -ArgumentList "app.py" -WindowStyle Minimized
          
          echo "Uygulamanın tam olarak açılması için 10 saniye bekleniyor..."
          Start-Sleep -Seconds 10
          
          echo "Hata ayıklama için ekran görüntüsü alınıyor..."
          Add-Type -AssemblyName System.Windows.Forms
          $bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
          $bitmap = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height
          $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
          $graphics.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)
          $bitmap.Save("debug-screenshot.png", [System.Drawing.Imaging.ImageFormat]::Png)
          
          echo "Otomasyon.exe çalıştırılıyor..."
          $process = Start-Process -FilePath "./test_run/Automation.exe" -PassThru -Wait -RedirectStandardOutput "stdout.txt" -RedirectStandardError "stderr.txt"
          
          $stdout = Get-Content stdout.txt -Raw -ErrorAction SilentlyContinue
          $stderr = Get-Content stderr.txt -Raw -ErrorAction SilentlyContinue
          $output = $stdout + $stderr
          
          echo "--- OTOMASYON ÇIKTISI (stdout + stderr) ---"
          echo $output
          echo "-------------------------------------------"
          
          $expected_text = "Kaydedildi! İsim: Barış Kahraman Yaş: 35"
          if ($output -like "*$expected_text*") {
            echo "✅ TEST BAŞARILI: Beklenen metin çıktıda bulundu."
            exit 0
          } else {
            echo "❌ TEST BAŞARISIZ: Beklenen metin çıktıda bulunamadı."
            echo "Okunan:"
            echo $output
            echo "Beklenen:"
            echo $expected_text
            exit 1
          }
      
      # Test başarısız olursa, hata ayıklama ekran görüntüsünü indirilebilir hale getirir
      - name: Upload Debug Screenshot on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: debug-screenshot.png
