name: Build, Test, and Release Automation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Extract Tesseract Portable
        run: |
          curl -L -o tesseract.zip "https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.3.3.20231005.exe"
          7z x tesseract.zip -oTesseractOCR

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run PyInstaller
        run: pyinstaller --name "Automation" --onefile --windowed --add-data "isim_label.png;." automation.py

      - name: Prepare Release Folder
        run: |
          mkdir release_package
          mkdir release_package/tesseract
          Copy-Item -Path "TesseractOCR/*" -Destination "release_package/tesseract" -Recurse
          Copy-Item -Path "dist/Automation.exe" -Destination "release_package/"
          Copy-Item -Path "isim_label.png" -Destination "release_package/"

      - name: Get Version Number
        id: version
        run: echo "tag=v1.0.${{ github.run_number }}" >> $env:GITHUB_OUTPUT

      - name: Zip Release Folder
        run: Compress-Archive -Path release_package/* -DestinationPath "InsaatAsistani-${{ steps.version.outputs.tag }}.zip"

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-package
          path: "InsaatAsistani-${{ steps.version.outputs.tag }}.zip"

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-release-package

      - name: Unzip Release Package
        run: Expand-Archive -Path "InsaatAsistani-${{ needs.build.outputs.version }}.zip" -DestinationPath test_run

      - name: Install and start virtual display
        run: |
          choco install tightvnc -y
          Start-Process "C:\Program Files\TightVNC\tvnserver.exe" -ArgumentList "-run"
          Start-Sleep -Seconds 5

      - name: Run Integration Test
        env:
          PYTHONUTF8: "1"
        run: |
          echo "Starting target application..."
          Start-Process python -ArgumentList "app.py" -WindowStyle Normal
          Start-Sleep -Seconds 5

          echo "Taking a debug screenshot..."
          Add-Type -AssemblyName System.Windows.Forms
          $bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
          $bitmap = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height
          $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
          $graphics.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)
          $bitmap.Save("debug-screenshot.png", [System.Drawing.Imaging.ImageFormat]::Png)

          echo "Running Automation.exe..."
          $process = Start-Process -FilePath "./test_run/Automation.exe" -PassThru -Wait -RedirectStandardOutput "stdout.txt" -RedirectStandardError "stderr.txt"
          
          $stdout = Get-Content stdout.txt -Raw -ErrorAction SilentlyContinue
          $stderr = Get-Content stderr.txt -Raw -ErrorAction SilentlyContinue
          $output = $stdout + $stderr
          
          echo "--- AUTOMATION OUTPUT ---"
          echo $output
          echo "--------------------------------"

          $expected_text = "Kaydedildi! Isim: Baris Kahraman Yas: 35"
          if ($output -like "*$expected_text*") {
            echo "✅ TEST PASSED"
            exit 0
          } else {
            echo "❌ TEST FAILED"
            echo $output
            exit 1
          }

      - name: Upload Debug Screenshot on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: debug-screenshot.png
